### ISSUE TITLE
Shen Repls share definitions

### ISSUE THREAD

**Issue by markokocic** [deech/shen-elisp#16]
Right now it is possible to create two shen repls, but they share the same definitions. Things defined in one are visible in other repl, which could be confusing and unexpecting from the user point of view.

I see there two possibilities:
- Make repls truly separate (might be either crazy hard or super easy, depending on how shen-elisp is implemented)
- Allow creation of only one Repl inside emacs

**Comment by deech** [comment]
Those are good thoughts. Currently anything evaluated at the REPL goes straight into the Emacs image. All Shen related things decompile with a `shen/` prefix. If you do `M-x describe-function shen/TAB` or `M-x describe-key shen/TAB` you can see them. Also doing `shen/repl` will go back to the REPL if it is open so the only way to have two REPLs is to delete one first. What I can do is keep history so it feels like a continuation of the old rather than a new REPL. What do you think?

**Comment by markokocic** [comment]
I understand, so it basically behave the same way as elisp, whatever and wherever you define, it's available everywhere. In that case limiting to one repl buffer makes perfect sense. Once that's clear, no need to further complicate by keeping history. Now that I tried again, I don't seem to be able to replicate how I got two working shen-elisp buffers. Will come back with exact steps once it happens again.
